import os
import platform

env = Environment(tools=['default','nidas'])

p1 = env.Program('ncprint','ncprint.cc',
    LIBS=["netcdf_c++","netcdf","hdf5","hdf5_hl","nidas_util"],
    CXXFLAGS=['-g','-Wall'])
#     CXXFLAGS=['-g','-pg','-Wall'],LINKFLAGS="-pg")


env['ISFF'] = os.environ['ISFF']

if platform.machine() == "x86_64":
    env['BINDIR'] = "bin64"
else:
    env['BINDIR'] = "bin"

env.Install('$ISFF/$BINDIR',p1)

env.Alias('install', [ '$ISFF/$BINDIR' ])
