import os
import subprocess

env = Environment(platform = 'posix')

env['ISFF'] = os.environ['ISFF']

kmach = subprocess.Popen(['uname','-m'],stdout=subprocess.PIPE).communicate()[0].rstrip("\n")
if kmach == "x86_64":
    env['BINDIR'] = "bin64"
    env['LIBDIR'] = "lib64"
else:
    env['BINDIR'] = "bin"
    env['LIBDIR'] = "lib"


# env['CCFLAGS'] = [ '-g', '-Wall', '-O2' ]

srcs = Split("""
    nc_server.cc
    nc_server_rpc_procs.cc
    nc_server_rpc_svc.c
""")

p1 = env.Program('ncprint','ncprint.cc',
    LIBS=["netcdf_c++","netcdf","hdf5","hdf5_hl",
        "nidas_util"],
    LIBPATH=["/opt/local/nidas/x86/" + env["LIBDIR"],"."],
    CPPPATH="/opt/local/nidas/x86/include",
    CXXFLAGS=['-g','-Wall'])
#     CXXFLAGS=['-g','-pg','-Wall'],LINKFLAGS="-pg")


env.Install('$ISFF/$BINDIR',p1)

env.Alias('install', [ '$ISFF/$BINDIR' ])
