import os
import subprocess

env = Environment(platform = 'posix',tools=['default','nidas'])

env['ISFF'] = os.environ['ISFF']

kmach = subprocess.Popen(['uname','-m'],stdout=subprocess.PIPE).communicate()[0].rstrip("\n")
if kmach == "x86_64":
    env['BINDIR'] = "bin64"
else:
    env['BINDIR'] = "bin"


# env['CCFLAGS'] = [ '-g', '-Wall', '-O2' ]

# env.Append(LIBPATH=".")

p1 = env.Program('ncprint','ncprint.cc',
    LIBS=["netcdf_c++","netcdf","hdf5","hdf5_hl","nidas_util"],
    CXXFLAGS=['-g','-Wall'])
#     CXXFLAGS=['-g','-pg','-Wall'],LINKFLAGS="-pg")


env.Install('$ISFF/$BINDIR',p1)

env.Alias('install', [ '$ISFF/$BINDIR' ])
