#!/bin/sh -e

# set the CLASSPATH to the jar files found in lib/linux

d=$(dirname $0)
[[ "$d" =~ \./.* ]] && d=$PWD/$d

cd $d/../../..

# cp=($d/lib/*.jar $d/lib/linux/*.jar)
cp=($d/lib/serializer.jar $d/lib/linux64/qtjambi-4.8.7.jar $d/lib/linux64/qtjambi-native-linux64-gcc-4.8.7.jar)
OLDIFS=$IFS
IFS=:
# This syntax for expanding an array expands to a single word
# with each member separated by the first character in IFS
export CLASSPATH="${cp[*]}"
IFS=$OLDIFS
echo "CLASSPATH=$CLASSPATH"

[ -d $d/classes ] || mkdir $d/classes

javac -d $d/classes \
    -Xlint \
    core/*.java \
    model/*.java \
    util/*.java  \
    ui/*.java \
    apps/cockpit/ui/*.java \
    apps/cockpit/model/*.java || exit 1

    # -Xlint -Xlint:unchecked \
    # -target 6 -source 6 -bootclasspath jdk1.7.0/lib/rt.jar \

jar cvfm cockpit.jar $d/manifest.txt $d/image/nodata.png -C $d/classes . || exit 1

