#!/bin/sh

# create a public/private key pair named "cockpit" in cockpit.keystore
# for signing jar files.

# validity parameter is number of days.

keytool -genkeypair -keystore javaws/cockpit.keystore -validity 730 \
    -dname "CN=Cockpit Developer, OU=EOL, O=NCAR, L=Boulder, S=Colorado, C=US" \
    -alias cockpit

echo "now check in javaws/cockpit.keystore to subversion"
