import eol_scons

from SCons.Script import Environment

env = Environment(tools=['default', 'buildmode', 'nidas'])

env.Append(CXXFLAGS=['-Wno-deprecated'])
p1 = env.Program("tt_adjust", ["tt_adjust.cc", "gsl.cc"])
